<a href="https://colab.research.google.com/github/assyifahnurlaeli/assyifahnurlaeli/blob/Porto/Daily_Corp_Sales_Reporting_Project_PT_Flexo_Solusi_Indonesia_(Reguler_%2B_Nurilab).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Input Data Needed
(Update yang perlu di update disini, misal tambah bulan July)

In [ ]:
# Input Bulan yang akan di report disini:
months_list = ['July','August','September']

# Input url spreadsheet untuk setiap bulan disini:
url_list = [
        ('July',"https://docs.google.com/spreadsheets/d/1Rboi4oZRxdkx3FqZ0qsXAWFAS_n5CLDjOc5f-C3Fr_w/edit?gid=0#gid=0"),
        ('August',"https://docs.google.com/spreadsheets/d/1MxxBnJl7IZgBZ2yofT3OLCcgsqlSC73EI9u_bh7upuE/edit?gid=0#gid=0"),
        ('September',"https://docs.google.com/spreadsheets/d/1QNheMH30tCnK-UqfiAOAdGY-P8-gZMEBrG2HHx_8bF8/edit?gid=0#gid=0")
    ]
url_list_nurilab = [
    ('July',"https://docs.google.com/spreadsheets/d/100MqtLySaVWfAxDzUnD1JvEwZP0mTGFao7cu9xrQRqw/edit?gid=0#gid=0"),
    ('August',"https://docs.google.com/spreadsheets/d/1Lrv__-LdWDi8UOdtWLMsJuK-nu4DdTgR8ewwS1DROhE/edit?gid=0#gid=0"),
    ('September',"https://docs.google.com/spreadsheets/d/1W6F9vzzMBBJzozfH4qyG8EbTMIxFbF-WY-1chqnEeCY/edit?gid=0#gid=0")
    ]
from datetime import datetime,timedelta

# Input start date disini:
start_date = '2025-05-01'

# end_date is today's date
today = datetime.today()+timedelta(hours=7)
today_date = today.strftime('%Y-%m-%d')
today_format = today.strftime('%d %B %Y')
end_date = today_date
month_format =  f'{months_list [0]} 2025 - {months_list [-1]} 2025'
# month_format = f'{months_list [0]} 2025'

url_month_1 = next(url for month, url in url_list if month == f'{months_list [0]}')
url_month_1_nurilab = next(url for month, url in url_list_nurilab if month == f'{months_list [0]}')
url_month_2 = next(url for month, url in url_list if month == f'{months_list [1]}')
url_month_2_nurilab = next(url for month, url in url_list_nurilab if month == f'{months_list [1]}')
url_month_3 = next(url for month, url in url_list if month == f'{months_list [2]}')
url_month_3_nurilab = next(url for month, url in url_list_nurilab if month == f'{months_list [2]}')

# edit weekly periode here (for rename the files)
# periode = '19 - 25 Mei 2023'

# Jangan diganti apapun
range_cell= 'A2:U200000'
init_cell = 'A2'

# Import Library Needed

In [ ]:
!pip install pretty_html_table
!pip install --upgrade gspread
!pip install xlsxwriter
import pandas as pd
import numpy as np
import datetime
import os
import time
import glob
from datetime import datetime, timedelta
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import gspread
from google.oauth2 import service_account
import json
import sys
import calendar
import math

import requests
import gspread
from oauth2client.client import GoogleCredentials
import openpyxl
import calendar
import time
import pandas as pd
import numpy as np
import gspread as gs

import os
import requests
from pprint import pprint
import json
import sys


#from google.colab import drive
#drive.mount('/content/drive')

Collecting pretty_html_table
  Downloading pretty_html_table-0.9.16-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pretty_html_table) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pretty_html_table) (1.17.0)
Downloading pretty_html_table-0.9.16-py3-none-any.whl (6.8 kB)
Installing collected packages: pretty_html_table
Successfully installed pretty_html_table-0.9.16
Requirement already satisfied: gspread in /usr/local/lib/python3.12/dist-packages (6.2.1)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from gspread) (2.38.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gspread) (1.2.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.12.0->gspread) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.12.0->gspread) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.12.0->gspread) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2025.8.3)
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.5-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.5-py3-none-any.whl (172 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.3/172.3 kB 3.9 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.5

# Function Used

In [ ]:
# Function Used
#gc= gspread.service_account_from_dict(credentials)


def poll_job(s, redash_url, job):
    # TODO: add timeout
    while job['status'] not in (3,4):
        response = s.get('{}/api/jobs/{}'.format(redash_url, job['id']))
        job = response.json()['job']
        time.sleep(5)

    if job['status'] == 3:
        return job['query_result_id']

    return None


def get_fresh_query_result(redash_url, query_id, api_key, params):
    s = requests.Session()
    s.headers.update({'Authorization': 'Key {}'.format(api_key)})

    payload = dict(max_age=0, parameters=params)

    response = s.post('{}/api/queries/{}/results'.format(redash_url, query_id), data=json.dumps(payload))

    if response.status_code != 200:
        return 'Refresh failed'
        raise Exception('Refresh failed.')

    result_id = poll_job(s, redash_url, response.json()['job'])

    if result_id:
        while True:
            try:
                response = s.get('{}/api/queries/{}/results/{}.json'.format(redash_url, query_id, result_id))
                break
            except:
                print('retry')

        if response.status_code != 200:
            raise Exception('Failed getting results.')
    else:
        raise Exception('Query execution failed.')

    return response.json()['query_result']['data']['rows']

In [ ]:
# Export to Google Sheets
credentials = {
  "type": "service_account",
  "project_id": "incentive-lh",
  "private_key_id": "7bdea8544907aec8759ea2adf1c77473cf7b2295",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC7pbOXFzSfjArl\nIV7oOVW+WIDFogpzIO0Nyl8sKNoNb0qK7Xkpz+o/y4gv0yBz8SFfiC9ISzCDGP7m\nkM6cNEgRjn6QrU30QTyhUvg/Y81PHIYNgO5xNtNgzNMpNpFfq+uHEf/TDLIjoMQj\nti/Y+GGCfOHn5oNGhKCCnvzhYSV4QaFJJE10DHrXszmPxsnE2/XShAZtK68oPjHn\nXoy76p8dg5ChnY3bN1wLLmz6WpyHcz7I91PBZMsd/wf+VIICm5QTcSoKecBP6brA\nYAMwkMV+30/ZEkXBNlZ/S1Vv/ciWdRX56crK3/msG3EpTUEISaYMgIRjvnkJTJ9f\nbzwDa2+hAgMBAAECggEAAfQUZckDzvpj/aUmigfYxOnCc2w/rBmmZhuaeIj3Vib3\nsXEN7xm/QElD4m2R+6sBtC8kgN3phB/dPXS59eXUbzxaxHJNarLIKQzGUVCeaUms\nepUCRnLx6eLP+vCavFJ7mfUdwupxq03H5PBHWLyjNTrMFkAv0yrbyehSTR1YCMOv\nk9sZOtAn9ogTOEPMqJHQYKOColfNwu8S1v7oFCEfiD2z5/lj2TKjH/PGGLMQB6rj\nD6cb1Ndi+0y2XGVYn7G3vagxmqYLXSzHIAGk67NR+veNfLkia45EeHimwOvumNKK\nC1jX1xEj6o4SEB0cpZ+Nm5D20bAnU/bAkM3Vqx94LQKBgQDgX2r1XfZPgnRvqZ4K\nZ4iiogzbEasHxAd3pW1ZuO8/XVIdQtuuQiW/DsqgLKU2enAX1Ow6/KAN+Re8WIcp\nayicfmcvW6q82Y8CLsxNca09JTBd+mGChlwHFpVZCJeGl/O/5lVJcV6U2sMV5vMT\nYtpOGRi0mFh0v5Y/WB96OUoPVQKBgQDWGQfUIfL7U7rlKcl31rjwJYg71Cl3vfSV\npZEc3BHrwxtZycYpTCb5Wjwx8BN+usZHfVA9Fzyw4RoUKr48VygiH7Xse7jGx9HW\nYvKTkHUlvrOO/MHIIVxRMhG9JoJMl7w0ES7vg1nQP2LRkyYEeG0ZbiwZeEumn8wg\nl//v9WrnHQKBgAM6fECBlJy6RNCigSqnKLkmWccBLxPSh0T6dWNYHOEth5PyNVUB\nkKd6IAJEAjCRfHFrV+bVYbwxvFyybWd0KkZuLy/oQsGq47rlT31ByHtbwKFpi+Oj\n6UkU0xtP21ZNc21sdAe1gOXla+8xvoel4XxEMi3PD17GrvPEYdeRYXZtAoGAFZ+D\njeY73yxOtPRqd6MFHKP9xWUhJwnVWQPWyx5i5PfYnFHnpKYfTZHSgIypu2PrwK6k\nWvcs1wR1GNJUUk3PLNsdCZxZRiJKTCfELikp270N74QRoj/UThMLfZoVEN1GUc/m\neKRAfurX9Siyb0MmaaoZ5BylL1f2SthvLfIQcPUCgYAcpOm4pui4Q6Os66na16im\nXd9/xBpUTtyN2qge0uRnLgW+UuZrF1cpdfvWiVKXbA21gesGRefGl054tF17o7kM\nBt2FM4Lfg6IGha1vsPV162w05qUNSaqDtgiQFpf9ULomtgVYB7CjmxJtjXaT5dD8\nnUqUcaLJj7DW2B023oQFUg==\n-----END PRIVATE KEY-----\n",
  "client_email": "dump-data@incentive-lh.iam.gserviceaccount.com",
  "client_id": "117090059571769919682",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dump-data%40incentive-lh.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}


gc = gs.service_account_from_dict(credentials)

def connect_to_sheet(url):
    #g_authorize = gspread.authorize(credentials())
    workbook = gc.open_by_url(url)

    return workbook


def connect_to_tab(url, tab_name):
    workbook = connect_to_sheet(url)
    tab = workbook.worksheet(tab_name)

    return tab

def clean_data(url, tab_name):
    workbook = connect_to_sheet(url)
    workbook.values_clear(f'{tab_name}')

    return print('Clean Succeed, Check your Gsheet')

def dump_data(data, url, tab_name, init_cell):
    workbook = connect_to_sheet(url)
    data = data.values.tolist()
    workbook.values_append(f'{tab_name}!'+init_cell,
                           {'valueInputOption': 'USER_ENTERED'},
                           {'values': data})

    return print('Dumping succeed, Check your Gsheet')

# Pulling Data from Redash

In [ ]:
# print('>> Pulling data from Redash...')
# loopcounter = 0
# while True:
#     try:
#         params = {'creation_end_date':end_date, 'creation_start_date':start_date, 'global_shipper_id':'10313516'}
#         api_key = 'KGy4OJdamBVI2gUWdjBfKgj8cpUETJwVqZPwb2Yf'
#         result = get_fresh_query_result('https://redash-id.ninjavan.co/',245, api_key, params)
#         print('>> Pulling data SUCCESS')
#         break
#     except:
#         print('Pulling data failed. Retrying..')
#         loopcounter = loopcounter +1
#         if loopcounter >=10:
#             break

# raw_data = pd.DataFrame(result)
# print("Total Order : ",raw_data.shape[0])
# # print("Number of Shipper with Order : ",raw_data['global_shipper_id'].nunique())

In [ ]:
print('>> Pulling data from Redash...')
shipper_ids = ['10313516', '10773880','10673505','10673521','10673537']  # List of shipper IDs
raw_data = pd.DataFrame()  # Initialize an empty DataFrame

for shipper_id in shipper_ids:
    loopcounter = 0
    while True:
        try:
            params = {
                'creation_end_date': end_date,
                'creation_start_date': start_date,
                'global_shipper_id': shipper_id
            }
            api_key = '6pbmI4eXJo4YaYaIVG3u48CL8qMEeD8LaWHu39tG'
            result = get_fresh_query_result(
                'https://redash-id.ninjavan.co/',
                245,
                api_key,
                params
            )
            print(f'>> Pulling data SUCCESS for Shipper ID: {shipper_id}')

            # Combine the new data with the existing DataFrame
            if result:
                raw_data = pd.concat([raw_data, pd.DataFrame(result)], ignore_index=True)
            break
        except Exception as e:
            print(f'Pulling data failed for Shipper ID {shipper_id}. Retrying... ({e})')
            loopcounter += 1
            if loopcounter >= 10:
                print(f'Failed to retrieve data for Shipper ID: {shipper_id}')
                break

print("Total Orders: ", raw_data.shape[0])
if not raw_data.empty:
    print("Number of Shippers with Orders: ", raw_data['global_shipper_id'].nunique())

>> Pulling data from Redash...
>> Pulling data SUCCESS for Shipper ID: 10313516
>> Pulling data SUCCESS for Shipper ID: 10773880
>> Pulling data SUCCESS for Shipper ID: 10673505
>> Pulling data SUCCESS for Shipper ID: 10673521
>> Pulling data SUCCESS for Shipper ID: 10673537
Total Orders:  19946
Number of Shippers with Orders:  2

In [ ]:
# raw_data.head()

In [ ]:
redash_245 = raw_data

In [ ]:
# redash_245

In [ ]:
# Extract order_id column as a list
list_order_id = redash_245['order_id'].tolist()

# Join the list elements into a comma-separated string with quotes around each element
listorderid = ",".join(f"'{str(order_id)}'" for order_id in list_order_id)

print(listorderid)

'1485329283','1485329284','1485329286','1485329287','1485329288','1485329290','1485329291','1485329292','1485329293','1485329294','1485329295','1485329296','1485329297','1485329298','1485329299','1485329300','1485329301','1485329305','1485329316','1485329322','1485329329','1485329330','1485329332','1485329335','1485329339','1485329340','1485329341','1485329342','1485329343','1485329344','1485329345','1485329346','1485329347','1485329348','1485329349','1485329350','1485329352','1485329353','1485329354','1485329355','1485329356','1485329357','1485329358','1485329359','1485329363','1485329365','1485329366','1485329367','1485329368','1485329369','1485329370','1485329371','1485329372','1485329373','1485329375','1485329376','1485329377','1485329378','1485329379','1485329381','1485329383','1485329384','1485329385','1485329386','1485329387','1485329388','1485329389','1485329390','1485329391','1485329392','1485329393','1485329394','1485329395','1485329396','1485329397','1485329398','1485329401','1485329403','1485329408','1485329413','1485329422','1485329435','1485329436','1485329437','1485329438','1485329439','1485329440','1485329444','1485329447','1485329452','1485329454','1485329456','1485329457','1485329458','1485329459','1485329460','1485329461','1485329463','1485329464','1485329465','1485329466','1485329468','1485329469','1485329470','1485329471','1485329472','1485329474','1485329475','1485329476','1485329477','1485329478','1485329479','1485329480','1485329481','1485329482','1485329484','1485329485','1485329486','1485329487','1485329497','1485329508','1485329510','1485329511','1485329513','1485329515','1485329517','1485329518','1485329519','1485329520','1485329521','1485329522','1485329523','1485329524','1485329525','1485329526','1485329528','1485329529','1485329532','1485329537','1485329544','1485329560','1485329561','1485329569','1485329571','1485329572','1485329573','1485329574','1485329575','1485329576','1485329578','1485329580','1485329581','1485329583','1485329585','1485329586','1485329587','1485329588','1485329589','1485329590','1485329591','1485329592','1485329593','1485329594','1485329595','1485329596','1485329597','1485329598','1485329599','1485329600','1485329601','1485329603','1485329604','1485329607','1485329608','1485329609','1485329610','1485329612','1485329613','1485329615','1485329616','1485329617','1485329618','1485329619','1485329622','1485329624','1485329633','1485329635','1485329642','1485329646','1485329648','1485329649','1485329650','1485329651','1485329652','1485329653','1485329654','1485329655','1485329656','1485329657','1485329658','1485329659','1485329660','1485329661','1485329662','1485329663','1485329664','1485329666','1485329667','1485329668','1485329670','1485329671','1485329672','1485329673','1485329675','1485329676','1485329677','1485329678','1485329680','1485329682','1485329684','1485329685','1485329686','1485329687','1485329688','1485329690','1485329691','1485329692','1485329693','1485329695','1485329696','1485329699','1485329703','1485329706','1485329709','1485329710','1485329711','1485329713','1485329715','1485329716','1485329717','1485329718','1485329719','1485329721','1485329723','1485329725','1485329726','1485329727','1485329728','1485329730','1485329731','1485329732','1485329733','1485329734','1485329735','1485329736','1485329737','1485329738','1485329739','1485329740','1485329741','1485329742','1485329743','1485329745','1485329746','1485329747','1485329748','1485329749','1485329750','1485329751','1485329752','1485329753','1485329754','1485329755','1485329757','1485329758','1485329759','1485329760','1485329761','1485329765','1485329771','1485329776','1485329780','1485329784','1485329786','1485329787','1485329788','1485329789','1485329790','1485329791','1485329792','1485329793','1485329794','1485329796','1485329797','1485329798','1485329799','1485329800','1485329801','1485329802','1485329803','1485329804','1485329805','1485329806','1485329807','1485329809','1485329810','1485329812','1485329813','1485329814','1485329815','1485329816','1485329817','1485329818','1485329819','1485329820','1485329821','1485329823','1485329824','1485329825','1485329826','1485329828','1485329829','1485329830','1485329831','1489073806','1489617849','1489092203','1489531565','1489531566','1489694925','1489694926','1491372900','1491372901','1491372902','1491372903','1491372904','1491372905','1491372906','1491372907','1491372909','1491372910','1491372911','1491372913','1491372914','1491372915','1491372916','1490200061','1490200063','1490259529','1491208004','1491208009','1491208010','1491208011','1489726516','1490207656','1490227067','1490227373','1491766858','1491766859','1493107355','1493287324','1493287325','1493287327','1493287328','1493287329','1493287330','1493287331','1493287334','1493287336','1493287338','1493287340','1493287341','1494404594','1492151545','1492151546','1492151548','1492151551','1492837267','1492837269','1491050258','1491050270','1491050274','1491050275','1491050276','1491050277','1491050278','1491050279','1491050280','1491050281','1491050282','1491050283','1491050284','1491050285','1491050286','1491050287','1491050288','1491050289','1491050292','1491050296','1491050300','1491050301','1491050302','1491050303','1491050304','1491050305','1491050307','1491050308','1491050309','1491050310','1491050311','1491050312','1491050313','1491050314','1491050315','1491050316','1491050317','1491050318','1491050319','1491050320','1491050322','1491050323','1491050324','1491050325','1491050326','1491050327','1491050328','1491050329','1491050330','1491050331','1491050332','1491050333','1491050334','1491050335','1491050336','1491050337','1491050338','1491050339','1491050340','1491050341','1491050342','1491050343','1491050344','1491050345','1491050346','1491050347','1491050348','1491050349','1491050351','1491050352','1491050353','1491050354','1491050355','1491050356','1491050357','1491050358','1491050359','1491050360','1491050361','1491050362','1491050363','1491050364','1491050365','1491050366','1491050367','1491050368','1491050369','1491050370','1491050371','1491050372','1491050373','1491050374','1491050375','1491050376','1491050377','1491050378','1491050379','1491050380','1491050381','1491050382','1491050383','1491050386','1491050387','1491050388','1491050389','1491050391','1491050392','1491050393','1491050394','1491050395','1491050396','1491050397','1491050399','1491050400','1491050401','1491050402','1491050403','1491050404','1491050405','1491050406','1491050408','1491050409','1491050410','1491050411','1491050413','1491050414','1491050415','1491050416','1491050417','1491050418','1491050419','1491050420','1491050421','1491050422','1491050423','1491050424','1491050425','1491050426','1491050427','1491423255','1491423256','1491423257','1491423258','1491423259','1491423260','1491423261','1491423262','1491423264','1491423265','1491423266','1491423267','1491423268','1491423269','1491423271','1491423272','1491423273','1491423274','1491423276','1491423277','1491423279','1491423280','1491423281','1491423282','1491423283','1491423284','1491423285','1491423286','1491423289','1491423290','1491423291','1491423292','1491423293','1491423294','1491423295','1491423296','1491423297','1491423298','1491423299','1491423300','1491423301','1491423302','1491423303','1491423304','1491423305','1491423306','1491423307','1491423308','1491423309','1491423310','1491423311','1491423312','1491423313','1491423314','1491423315','1491423316','1491423317','1491423318','1491423319','1491423321','1491423328','1491423336','1491423339','1491423340','1491423342','1491423343','1491423344','1491423345','1491423346','1491423347','1491423348','1491423349','1491423350','1491423351','1491423352','1491423353','1491423354','1491423355','1491423357','1491423358','1491423359','1491423360','1491423361','1491423362','1491423363','1491423364','1491423365','1491423366','1491423367','1491423368','1491423369','1491423370','1491423371','1491423372','1491423374','1491423375','1491423376','1491423377','1491423378','1491423379','1491423380','1491423382','1491423383','1491423384','1491423385','1491423386','1491423387','1491423388','1491423389','1491423390','1491423391','1491423392','1491423394','1491423397','1491423398','1491423400','1491423401','1491423402','1491423403','1491423404','1491423405','1491423406','1491423407','1491423409','1491423410','1491423411','1491423412','1491423413','1491423414','1491423415','1491423416','1491423417','1491423418','1491423419','1491423420','1491423421','1491423422','1491423423','1491423424','1490264368','1490264369','1490264370','1490264371','1490264372','1490264376','1490264377','1490264378','1490264380','1490264381','1490264382','1490264385','1490264386','1490264387','1490264388','1490264389','1490264390','1490264391','1490264394','1490264395','1490264398','1490264400','1490264401','1490264402','1490264403','1490264404','1490264405','1490264406','1490264415','1490264436','1490264466','1490264480','1490264501','1490264513','1490264515','1490264516','1490264519','1490264553','1490264573','1490264601','1490264613','1490264630','1490264631','1490264632','1490264634','1490264635','1490264637','1490264641','1490264653','1490264678','1490264679','1490264681','1490264682','1490264683','1490264685','1490264686','1490264687','1490264690','1490264691','1490264692','1490264694','1490264695','1490264696','1490264697','1490264698','1490264699','1490264700','1490264701','1490264702','1490264703','1490264704','1490264705','1490264706','1490264707','1490671071','1490671072','1490671074','1490671075','1490671076','1490671077','1490671079','1490671080','1490671081','1490671082','1490671083','1490671084','1490671085','1490671086','1490671087','1490671088','1490671089','1490671090','1490671091','1490671092','1490671093','1490671094','1490671096','1490671097','1490671098','1490671099','1490671100','1490671101','1490671102','1490671103','1490671104','1490671106','1490671108','1490671109','1490671110','1490671111','1490671112','1490671113','1490671114','1490671115','1490671116','1490671117','1490671118','1490671119','1490671120','1490671121','1490671123','1490671124','1490671125','1490671126','1490671128','1490671129','1490671130','1490671131','1490671132','1490671133','1490671134','1490671135','1490671136','1490671137','1490671138','1490671139','1490671140','1490671141','1490671142','1490671143','1490671144','1490671145','1490671146','1490671147','1490671148','1490671149','1490671150','1490671151','1490671152','1490671153','1490671154','1490671155','1490671156','1490671157','1490671158','1490671160','1490671161','1490671162','1490671163','1490671164','1490671165','1490671166','1490671167','1490671168','1490671170','1490671172','1490671173','1490671175','1490671176','1490671178','1490671179','1490671180','1490671181','1490671182','1490671183','1490671184','1490671185','1490671186','1490671188','1490671189','1490671191','1490671192','1490671193','1490671195','1490671196','1490671197','1490671198','1490671199','1490671200','1490671201','1490671202','1490671203','1490671204','1490671205','1490671206','1490671207','1490671208','1490671209','1490671210','1490671211','1490671213','1490671214','1490671215','1490671216','1490671217','1490671218','1490671219','1490671220','1490671221','1490671222','1490671223','1490671224','1490671225','1490671226','1490671227','1490671228','1490671229','1490671231','1490671232','1490671233','1490671235','1490671236','1490675188','1490675189','1490675190','1490675191','1489112660','1489112661','1489112662','1489112663','1489112665','1489112666','1489112667','1489112668','1489112669','1489112670','1489112671','1489112672','1489112673','1489112675','1489112676','1489112677','1489112679','1493911214','1493911215','1493911216','1493911217','1493911218','1493911219','1493911220','1493911221','1493911223','1493911224','1493911250','1493911266','1493911271','1493911272','1493911273','1493911275','1493911277','1493911278','1493911279','1493911280','1493911283','1493911284','1493911285','1493911287','1493911288','1493911289','1493911291','1493911306','1493911309','1493911310','1493917396','1490251463','1490251464','1491025201','1491025202','1491025203','1491025204','1491025205','1491025206','1491025207','1491025208','1491025209','1491025210','1491025211','1491025212','1491025213','1491025214','1491025215','1492825956','1492825959','1492825960','1492890395','1492890396','1492890397','1492890398','1492890399','1492890401','1492890402','1492890404','1492890405','1492890423','1492890427','1492890428','1492890429','1492890430','1492890431','1492890432','1492890433','1492890434','1492890440','1492890441','1492890442','1492890443','1492890444','1492890445','1492890447','1492890450','1492890451','1492890453','1492890454','1492890455','1492890456','1492890457','1492890458','1492890460','1492890462','1492890463','1492890466','1492890467','1492890468','1492890469','1492890470','1492890471','1492890472','1492890473','1492890474','1492890475','1492890476','1492890477','1492890478','1492890479','1492890480','1492890481','1492890482','1492890483','1492890484','1492890485','1492890486','1492890487','1492890488','1492890489','1492890490','1492890491','1492890492','1492890493','1492890494','1492890495','1492890496','1492890497','1492890498','1492890499','1492890500','1492890501','1492890502','1488338550','1488338551','1488338552','1488338553','1488338554','1488338556','1488338558','1488338559','1488338560','1488338563','1488338565','1488338566','1488338567','1488338568','1488338569','1488338570','1488338571','1488338572','1488338573','1488338574','1488338575','1488338576','1488338577','1488338578','1488338579','1488338580','1488338581','1488338582','1488338583','1488338584','1488338585','1488338586','1488338587','1488338588','1488338589','1488338590','1488338591','1488338592','1488338593','1488338594','1488338597','1488338598','1488338600','1488338601','1488338604','1488338606','1488338608','1488338610','1488338611','1488338612','1488338614','1488338615','1488338616','1488338619','1488338623','1488338628','1488338630','1488338631','1486831327','1486831329','1486831330','1486831331','1486831332','1486831333','1486831334','1486831335','1486831336','1486831337','1486831338','1486831340','1486831341','1486831343','1486831344','1486831345','1486831346','1486831347','1486831348','1486831349','1486831350','1486831351','1486831352','1486831353','1486831354','1486831355','1486831356','1486831357','1486831358','1486831359','1486831360','1486831362','1486831364','1486831365','1486831366','1486831367','1486831368','1486831369','1486831370','1486831371','1486831372','1486831374','1486831378','1486831379','1486831380','1486831381','1486831382','1486831383','1486831384','1486831385','1486831386','1486831387','1486832370','1486835813','1486835814','1486835816','1486835817','1486835818','1486835820','1486835821','1486835822','1486835823','1486835824','1486835825','1486835827','1486835838','1486835849','1486835854','1486835855','1486835857','1486835858','1486835859','1486835860','1486835862','1486835865','1486835866','1486835868','1486835871','1486835876','1486835878','1486835881','1486835883','1486835884','1486835885','1486835886','1486835887','1486835888','1486835889','1486835890','1486835891','1486835893','1486835894','1486835895','1486835896','1486835897','1486835898','1486835899','1486835901','1486835902','1486835903','1486835904','1486835905','1486835906','1486835907','1486835908','1486835909','1486835910','1486835911','1486835912','1486835913','1486835914','1486835915','1486835916','1486835917','1486835918','1486835919','1486835920','1486835921','1486835923','1486835924','1486835925','1486835926','1486835927','1486835928','1486835929','1486835930','1486835931','1486835932','1486835935','1486835936','1486835937','1486835938','1486835940','1487316772','1487316773','1487316774','1487316775','1487316776','1487316777','1487316778','1487316780','1487316781','1487316782','1487316783','1487316784','1487316785','1487316786','1487316787','1487316788','1487316789','1487316790','1487316791','1487316793','1487316794','1487316795','1487316797','1487316799','1487316800','1487316801','1487316803','1487316805','1487316808','1487316809','1487316810','1487316811','1487316812','1487316813','1487316814','1487316815','1487316816','1487316817','1487316818','1487316819','1487316820','1487316822','1487316823','1487316824','1487316825','1487316826','1487316827','1487316828','1487316831','1487316832','1487316833','1487316835','1487316837','1487316838','1487316839','1487316840','1487316841','1487316842','1487316843','1487316844','1487316845','1487316846','1487316847','1487316849','1487316850','1487316852','1487316854','1487316855','1487316856','1487316857','1487316859','1487316860','1487316861','1487316863','1487316865','1487316867','1487316868','1487316869','1487316872','1487316873','1487316875','1487316876','1487316877','1487316878','1487316879','1487316881','1487316883','1487316885','1487316886','1487316887','1487318261','1487318262','1487318263','1487318264','1487318265','1487318266','1487318267','1487318268','1487318269','1487318270','1487318271','1487318272','1487318273','1487318274','1487318275','1487318276','1487318277','1487318278','1487318279','1487318281','1487318282','1487318283','1487318285','1487318287','1487318288','1487318289','1487318292','1487318293','1487318294','1487318295','1487318297','1487318299','1487318300','1487318301','1487318303','1487318304','1487318305','1487318306','1487318307','1487318309','1487318310','1487318312','1487318313','1487318314','1487318315','1487318317','1487318318','1487318319','1487318320','1487318321','1487318322','1487318323','1487318324','1487318325','1487318326','1487318327','1487318328','1487318329','1487318330','1487318332','1487318333','1487318334','1487318337','1487318339','1487318341','1487318342','1487318343','1487318344','1487318345','1487318346','1487318347','1487318349','1487318351','1487318354','1487318355','1487318356','1487318358','1487318359','1487318360','1487318365','1487318371','1487318375','1487318377','1487318379','1487318380','1487318381','1487318382','1487318383','1487318384','1487318385','1487318386','1487318387','1487318388','1487318390','1487318391','1487318393','1487318394','1487318395','1487318397','1487318398','1487318399','1487318400','1487318401','1487318403','1487318404','1487318405','1487318406','1487318407','1487318408','1487318409','1488753719','1488753721','1488753722','1488753723','1488753724','1488753726','1488753727','1488753728','1488753729','1488753730','1488753731','1488753732','1488753733','1488753735','1488753736','1488753737','1488753739','1488753740','1488753742','1488753744','1488753746','1488753748','1488753751','1488753754','1488753756','1488753757','1488753759','1488753761','1488753763','1488753766','1488753769','1488753773','1488753777','1488753783','1488753789','1488753791','1488753792','1488753794','1488753797','1488753800','1488753801','1488753802','1488753803','1488753804','1488753805','1488753806','1488753807','1488753808','1488753809','1488753810','1488753811','1488753812','1488753813','1488753814','1488753815','1488753816','1488753817','1488753818','1488753819','1488753820','1488753821','1488753822','1485741376','1485741378','1485741381','1485741382','1485741383','1485741384','1485741385','1485741387','1485741390','1485741392','1485741402','1485741403','1485741409','1485741412','1485741418','1485741427','1485741433','1485741439','1485741446','1485741448','1485741450','1485741451','1485741452','1485741454','1485741458','1485741459','1485741460','1485741461','1485741463','1485741465','1485741467','1485741469','1485741471','1485741472','1485741473','1485741475','1485741476','1485741483','1485741493','1485741498','1485741499','1485741500','1485741503','1485741504','1485741507','1485741508','1485741509','1485741511','1485741512','1485741514','1485741515','1485741516','1485741519','1485741520','1485741521','1485741523','1485741524','1485741525','1485741527','1485741528','1485741529','14857

In [ ]:
print('>> Pulling data from Redash...')
loopcounter = 0
while True:
    try:
        params = {'order_id':listorderid}
        api_key = '6pbmI4eXJo4YaYaIVG3u48CL8qMEeD8LaWHu39tG'
        result = get_fresh_query_result('https://redash-id.ninjavan.co/',365, api_key, params)
        print('>> Pulling data SUCCESS')
        break
    except:
        print('Pulling data failed. Retrying..')
        loopcounter = loopcounter +1
        if loopcounter >=10:
            break

raw_data = pd.DataFrame(result)
print("Total Order : ",raw_data.shape[0])
# print("Number of Shipper with Order : ",raw_data['global_shipper_id'].nunique())

>> Pulling data from Redash...
>> Pulling data SUCCESS
Total Order :  19946

In [ ]:
new_order = ['tracking_id','total_fee','nv_dimensions','weight']

redash_365= raw_data[new_order]

# Add data Actual SLA days

In [ ]:
sla = pd.read_csv("/content/Flexo_SLA.csv")

In [ ]:
sla_fix = sla[['tracking_id','from_l2_name','to_l2_name','sla_days']]

# Data Manipulation

In [ ]:
print(">> Data manipulation for flexo start...")

# change data type to datetime
redash_245[['order_creation_datetime','first_inbound_datetime','pod_datetime']] = redash_245[['order_creation_datetime','first_inbound_datetime','pod_datetime']].apply(pd.to_datetime)

# get month
redash_245['month'] = redash_245['order_creation_datetime'].dt.month
month_mapping = {i: calendar.month_name[i] for i in range(1, 13)}
redash_245['month'] = redash_245['month'].map(month_mapping)


flexo_data = redash_245

# Change format datetime to mm-dd-yyyy
flexo_data['order_creation_datetime'] = pd.to_datetime(flexo_data['order_creation_datetime']).dt.strftime('%m/%d/%Y')
flexo_data['first_inbound_datetime'] = pd.to_datetime(flexo_data['first_inbound_datetime']).dt.strftime('%m/%d/%Y')
flexo_data['pod_datetime'] = pd.to_datetime(flexo_data['pod_datetime']).dt.strftime('%m/%d/%Y')


# # # make new column shipper_reference_no
# # kbg_data['shipper_reference_no']= kbg_data['tracking_id'].str[-16:]

# fill last fail reason
flexo_data['last_fail_reason'] = np.where(flexo_data['last_fail_reason'].isna(), flexo_data['rts_flag'], flexo_data['last_fail_reason'])

# filter data nurilab only
flexo_data = redash_245[redash_245["global_shipper_id"] == 10673505]
# Get All Column needed
flexo_data = redash_245[['order_creation_datetime',
                     'tracking_id',	'global_shipper_id', 'shipper_name','shipper_reference_no',
                     'to_address',	'rts_flag',
                     'granular_status',	'to_name',
                     'to_contact',	'instruction',
                     'first_inbound_datetime',
                     'last_fail_reason',
                     'pod_datetime',
                     'pod_recipient_name',
                     'pod_photo_url','no_of_attempt','month']]
flexo_data.head()

# Merge KBG_plain with redash_365
flexo_data = flexo_data.merge(redash_365[['tracking_id', 'total_fee', 'nv_dimensions','weight']], on='tracking_id', how='left')

# Merge KBG_plain with sla_days(from metabase)
flexo_data = flexo_data.merge(sla_fix, on='tracking_id', how='left')

# change datatype for json
for col in (flexo_data.select_dtypes(include=['float64','datetime64'])).columns:
    flexo_data[col] = flexo_data[col].astype(str)

flexo_data = flexo_data.fillna('')

flexo_data.head()


# print("Data manipulation flexo DONE")

>> Data manipulation for flexo start...

,order_creation_datetime,tracking_id,global_shipper_id,shipper_name,shipper_reference_no,to_address,rts_flag,granular_status,to_name,to_contact,...,pod_recipient_name,pod_photo_url,no_of_attempt,month,total_fee,nv_dimensions,weight,from_l2_name,to_l2_name,sla_days
0,05/07/2025,FTJKT210025231,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025231-01,"CIBINONG, BOGOR (apotek alfalah cikaret) Jl. A...",Non RTS,Completed,GITHE ADE RIA,+6285156596620,...,"""GITHE ADE RIA""",https://api.ninjavan.co/assets/f71bf634-3f24-4...,1,May,4044,13.73 x 7.8 x 23.378,1.0,,,nan
1,05/07/2025,FTJKT210025235,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025235-01,"Jln sosor Baringin, lintong nihuta, tampahan, ...",Non RTS,Completed,ELISA SITOHANG,+6283149648672,...,"""ELISA SITOHANG""",https://api.ninjavan.co/assets/e668dbb3-e4d3-4...,1,May,26184.9,13.484 x 7.2 x 23.538,1.0,,,nan
2,05/07/2025,FTJKT210025236,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025236-01,"kampung kebon kopi, desa ciampea udik, kecamat...",Non RTS,Completed,FATHU LANGIT,+6283174592799,...,"""FATHU LANGIT""",https://api.ninjavan.co/assets/9d2885b4-f5b3-4...,1,May,4044,13.588 x 7.3 x 23.422,1.0,,,nan
3,05/07/2025,FTJKT210025237,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025237-01,jl. Kapten Dasuki Bakri gang jagal ayam kp Bab...,Non RTS,Completed,TIA UTAMI,+6285710575368,...,"""adiknya""",https://api.ninjavan.co/assets/b7e96c63-772b-4...,1,May,4044,13.362 x 7.5 x 23.199,1.0,,,nan
4,05/07/2025,FTJKT210025238,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025238-01,"Percetakan Ummy, JL.Mualimin RT/RW 009/004 Kel...",Non RTS,Completed,BELLA,+62819181515,...,"""BELLA""",https://api.ninjavan.co/assets/bc763fcc-c359-4...,1,May,31138.8,13.391 x 7.3 x 22.973,1.0,,,nan

In [ ]:
pd.set_option('display.max_columns', None)
flexo_data.head()

,order_creation_datetime,tracking_id,global_shipper_id,shipper_name,shipper_reference_no,to_address,rts_flag,granular_status,to_name,to_contact,instruction,first_inbound_datetime,last_fail_reason,pod_datetime,pod_recipient_name,pod_photo_url,no_of_attempt,month,total_fee,nv_dimensions,weight,from_l2_name,to_l2_name,sla_days
0,05/07/2025,FTJKT210025231,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025231-01,"CIBINONG, BOGOR (apotek alfalah cikaret) Jl. A...",Non RTS,Completed,GITHE ADE RIA,+6285156596620,KOL,05/08/2025,Non RTS,05/10/2025,"""GITHE ADE RIA""",https://api.ninjavan.co/assets/f71bf634-3f24-4...,1,May,4044,13.73 x 7.8 x 23.378,1.0,,,nan
1,05/07/2025,FTJKT210025235,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025235-01,"Jln sosor Baringin, lintong nihuta, tampahan, ...",Non RTS,Completed,ELISA SITOHANG,+6283149648672,KOL,05/08/2025,Non RTS,05/14/2025,"""ELISA SITOHANG""",https://api.ninjavan.co/assets/e668dbb3-e4d3-4...,1,May,26184.9,13.484 x 7.2 x 23.538,1.0,,,nan
2,05/07/2025,FTJKT210025236,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025236-01,"kampung kebon kopi, desa ciampea udik, kecamat...",Non RTS,Completed,FATHU LANGIT,+6283174592799,KOL,05/08/2025,Non RTS,05/10/2025,"""FATHU LANGIT""",https://api.ninjavan.co/assets/9d2885b4-f5b3-4...,1,May,4044,13.588 x 7.3 x 23.422,1.0,,,nan
3,05/07/2025,FTJKT210025237,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025237-01,jl. Kapten Dasuki Bakri gang jagal ayam kp Bab...,Non RTS,Completed,TIA UTAMI,+6285710575368,KOL,05/08/2025,Non RTS,05/10/2025,"""adiknya""",https://api.ninjavan.co/assets/b7e96c63-772b-4...,1,May,4044,13.362 x 7.5 x 23.199,1.0,,,nan
4,05/07/2025,FTJKT210025238,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025238-01,"Percetakan Ummy, JL.Mualimin RT/RW 009/004 Kel...",Non RTS,Completed,BELLA,+62819181515,KOL,05/08/2025,Non RTS,05/10/2025,"""BELLA""",https://api.ninjavan.co/assets/bc763fcc-c359-4...,1,May,31138.8,13.391 x 7.3 x 22.973,1.0,,,nan

# Clean and Dumping Data to Google Sheets

(NOTE: Report ini dikirim dalam bentuk link Google Sheets)

In [ ]:
start = time.time()

import math

range_cell = 'A2:U337000'
init_cell = 'A2'
chunk_size = 50000  # Define the chunk size

for month in months_list:
    # Filter kbg_data_plain for the current month
    filtered_data_flexo = flexo_data[flexo_data['month'] == month].copy()

    # Drop the "month" column
    filtered_data_flexo.drop('month', axis=1, inplace=True)

    # Find the corresponding URL for the current month
    url = next((url for name, url in url_list if name == month), None)

    # Clean the data in the Google Sheet
    range_delete_flexo = f'{month}!' + range_cell
    clean_data(url, range_delete_flexo)
    print(f'Cleaned {month} flexo DONE')

    # Dump Data into Google Sheet
    tab_name_dump_flexo = f'{month}'

    # Calculate the number of chunks needed
    num_chunks = math.ceil(len(filtered_data_flexo) / chunk_size)

    # Iterate over the chunks
    for i in range(num_chunks):
        start_row = i * chunk_size
        end_row = start_row + chunk_size

        # Get the chunk of data
        chunk_data = filtered_data_flexo.iloc[start_row:end_row]

        # Specify the range to append the data
        append_range = f'{tab_name_dump_flexo}'

        # Dump the chunk of data to the sheet
        dump_data(chunk_data, url, append_range, init_cell)

        print(f'Dumped chunk {i + 1}/{num_chunks} for {month} Flexo DONE')

end = time.time()
print("CSV:", end - start)

print('ALL LOOPING DONE')

Clean Succeed, Check your Gsheet
Cleaned July flexo DONE
Dumping succeed, Check your Gsheet
Dumped chunk 1/1 for July Flexo DONE
Clean Succeed, Check your Gsheet
Cleaned August flexo DONE
Dumping succeed, Check your Gsheet
Dumped chunk 1/1 for August Flexo DONE
Clean Succeed, Check your Gsheet
Cleaned September flexo DONE
Dumping succeed, Check your Gsheet
Dumped chunk 1/1 for September Flexo DONE
CSV: 11.619510650634766
ALL LOOPING DONE

# Data Manipulation NURILAB

In [ ]:
print(">> Data manipulation start...")

# change data type to datetime
redash_245[['order_creation_datetime','first_inbound_datetime','pod_datetime']] = redash_245[['order_creation_datetime','first_inbound_datetime','pod_datetime']].apply(pd.to_datetime)

# get month
redash_245['month'] = redash_245['order_creation_datetime'].dt.month
month_mapping = {i: calendar.month_name[i] for i in range(1, 13)}
redash_245['month'] = redash_245['month'].map(month_mapping)

# # Get All Column needed
# kbg_data = redash_245[['order_creation_datetime',
#                      'tracking_id',	'shipper_reference_no', 'to_name',
#                      'to_address', 'to_contact',	'rts_flag',
#                      'granular_status',	'to_name',
#                      'to_contact',	'instruction',
#                      'first_inbound_datetime',
#                      'last_fail_reason',
#                      'pod_datetime',
#                      'pod_recipient_name',
#                      'pod_photo_url','no_of_attempt','month',]]


# Change format datetime to mm-dd-yyyy
redash_245['order_creation_datetime'] = pd.to_datetime(redash_245['order_creation_datetime']).dt.strftime('%m/%d/%Y')
redash_245['first_inbound_datetime'] = pd.to_datetime(redash_245['first_inbound_datetime']).dt.strftime('%m/%d/%Y')
redash_245['pod_datetime'] = pd.to_datetime(redash_245['pod_datetime']).dt.strftime('%m/%d/%Y')

# make new column shipper_reference_no
# kbg_data['shipper_reference_no']= kbg_data['tracking_id'].str[-16:]

# fill last fail reason
redash_245['last_fail_reason'] = np.where(redash_245['last_fail_reason'].isna(), redash_245['rts_flag'], redash_245['last_fail_reason'])

# filter data nurilab only
nurilab_data = redash_245[redash_245["global_shipper_id"] != 10673505]

# Merge nurilab with redash_365 (add dimensions, weight)
nurilab_data = nurilab_data.merge(redash_365[['tracking_id', 'total_fee', 'nv_dimensions','weight']], on='tracking_id', how='left')

# Merge nurilab with sla_days(from metabase)
nurilab_data = nurilab_data.merge(sla_fix, on='tracking_id', how='left')

# add data status_paket
nurilab_data['Status_paket'] = np.select(
    [nurilab_data['granular_status'] == 'Completed',nurilab_data['granular_status'] == 'Returned to Sender'],
    ['Success Delivery','RTS'],
    default='In Progress')


# Get All Column needed
nurilab_data = nurilab_data[['order_creation_datetime',
                     'tracking_id',	'global_shipper_id','shipper_name','shipper_reference_no', 'to_name',
                     'to_address', 'to_contact','to_l2_name',	'pod_photo_url','Status_paket','granular_status',
                     'pod_datetime',
                    'rts_flag','no_of_attempt','order_comments',
                      'first_fail_reason',
                     'last_fail_reason',
                     'month','total_fee', 'nv_dimensions','weight','from_l2_name','to_l2_name','sla_days','instruction']]
# Add Note Flexo
nurilab_data['Note FLexo'] = np.where(nurilab_data['order_creation_datetime'].notna(), "NURILAB","")

# # change datatype for json
# for col in (nurilab_data.select_dtypes(include=['float64','datetime64'])).columns:
#     nurilab_data[col] = nurilab_data[col].astype(str)

# nurilab_data = nurilab_data.fillna('')

print("Data manipulation DONE")

>> Data manipulation start...
Data manipulation DONE

In [ ]:
nurilab_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19147 entries, 0 to 19146
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_creation_datetime  19147 non-null  object
 1   tracking_id              19147 non-null  object
 2   global_shipper_id        19147 non-null  int64
 3   shipper_name             19147 non-null  object
 4   shipper_reference_no     18817 non-null  object
 5   to_name                  19147 non-null  object
 6   to_address               19147 non-null  object
 7   to_contact               19147 non-null  object
 8   to_l2_name               13770 non-null  object
 9   pod_photo_url            19019 non-null  object
 10  Status_paket             19147 non-null  object
 11  granular_status          19147 non-null  object
 12  pod_datetime             19024 non-null  object
 13  rts_flag                 19147 non-null  object
 14  no_of_attempt            19147 non-null  int64
 15  order_comments           271 non-null    object
 16  first_fail_reason        1746 non-null   object
 17  last_fail_reason         19147 non-null  object
 18  month                    19147 non-null  object
 19  total_fee                18721 non-null  object
 20  nv_dimensions            19147 non-null  object
 21  weight                   19147 non-null  float64
 22  from_l2_name             13739 non-null  object
 23  to_l2_name               13770 non-null  object
 24  sla_days                 13739 non-null  float64
 25  instruction              19087 non-null  object
 26  Note FLexo               19147 non-null  object
dtypes: float64(2), int64(2), object(23)
memory usage: 3.9+ MB

In [ ]:
pd.set_option('display.max_columns', None)
nurilab_data.head()

,order_creation_datetime,tracking_id,global_shipper_id,shipper_name,shipper_reference_no,to_name,to_address,to_contact,to_l2_name,pod_photo_url,Status_paket,granular_status,pod_datetime,rts_flag,no_of_attempt,order_comments,first_fail_reason,last_fail_reason,month,total_fee,nv_dimensions,weight,from_l2_name,to_l2_name,sla_days,instruction,Note FLexo
0,05/07/2025,FTJKT210025231,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025231-01,GITHE ADE RIA,"CIBINONG, BOGOR (apotek alfalah cikaret) Jl. A...",+6285156596620,NaN,https://api.ninjavan.co/assets/f71bf634-3f24-4...,Success Delivery,Completed,05/10/2025,Non RTS,1,None,None,Non RTS,May,4044,13.73 x 7.8 x 23.378,1.0,NaN,NaN,NaN,KOL,NURILAB
1,05/07/2025,FTJKT210025235,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025235-01,ELISA SITOHANG,"Jln sosor Baringin, lintong nihuta, tampahan, ...",+6283149648672,NaN,https://api.ninjavan.co/assets/e668dbb3-e4d3-4...,Success Delivery,Completed,05/14/2025,Non RTS,1,None,None,Non RTS,May,26184.9,13.484 x 7.2 x 23.538,1.0,NaN,NaN,NaN,KOL,NURILAB
2,05/07/2025,FTJKT210025236,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025236-01,FATHU LANGIT,"kampung kebon kopi, desa ciampea udik, kecamat...",+6283174592799,NaN,https://api.ninjavan.co/assets/9d2885b4-f5b3-4...,Success Delivery,Completed,05/10/2025,Non RTS,1,None,None,Non RTS,May,4044,13.588 x 7.3 x 23.422,1.0,NaN,NaN,NaN,KOL,NURILAB
3,05/07/2025,FTJKT210025237,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025237-01,TIA UTAMI,jl. Kapten Dasuki Bakri gang jagal ayam kp Bab...,+6285710575368,NaN,https://api.ninjavan.co/assets/b7e96c63-772b-4...,Success Delivery,Completed,05/10/2025,Non RTS,1,None,None,Non RTS,May,4044,13.362 x 7.5 x 23.199,1.0,NaN,NaN,NaN,KOL,NURILAB
4,05/07/2025,FTJKT210025238,10773880,PT Flexo Solusi Indonesia - Regular (B2BR),FTJKT210025238-01,BELLA,"Percetakan Ummy, JL.Mualimin RT/RW 009/004 Kel...",+62819181515,NaN,https://api.ninjavan.co/assets/bc763fcc-c359-4...,Success Delivery,Completed,05/10/2025,Non RTS,1,None,None,Non RTS,May,31138.8,13.391 x 7.3 x 22.973,1.0,NaN,NaN,NaN,KOL,NURILAB

# Clean and Dumping Data to Google Sheets for NURILAB

(NOTE: Report ini dikirim dalam bentuk link Google Sheets)

In [ ]:
# change datatype for json
for col in (nurilab_data.select_dtypes(include=['float64','datetime64'])).columns:
    nurilab_data[col] = nurilab_data[col].astype(str)

nurilab_data = nurilab_data.fillna('')

In [ ]:
start = time.time()

import math

range_cell = 'A2:Y100000'
init_cell = 'A2'
chunk_size = 50000  # Define the chunk size

for month in months_list:
    # Filter kbg_data_plain for the current month
    nurilab_data_month = nurilab_data[nurilab_data['month'] == month].copy()

    # Drop the "month" column
    nurilab_data_month.drop('month', axis=1, inplace=True)

    # Find the corresponding URL for the current month
    url = next((url for name, url in url_list_nurilab if name == month), None)

    # Clean the data in the Google Sheet
    range_delete = f'{month}!' + range_cell
    clean_data(url, range_delete)
    print(f'Cleaned {month} Nurilab DONE')

    # Dump Data into Google Sheet
    tab_name_dump_nurilab = f'{month}'

    # Calculate the number of chunks needed
    num_chunks = math.ceil(len(nurilab_data_month) / chunk_size)

    # Iterate over the chunks
    for i in range(num_chunks):
        start_row = i * chunk_size
        end_row = start_row + chunk_size

        # Get the chunk of data
        chunk_data = nurilab_data_month.iloc[start_row:end_row]

        # Specify the range to append the data
        append_range = f'{tab_name_dump_nurilab}'

        # Dump the chunk of data to the sheet
        dump_data(chunk_data, url, append_range, init_cell)

        print(f'Dumped chunk {i + 1}/{num_chunks} for {month} nurilab DONE')

end = time.time()
print("CSV:", end - start)

print('ALL LOOPING DONE')

Clean Succeed, Check your Gsheet
Cleaned July Nurilab DONE
Dumping succeed, Check your Gsheet
Dumped chunk 1/1 for July nurilab DONE
Clean Succeed, Check your Gsheet
Cleaned August Nurilab DONE
Dumping succeed, Check your Gsheet
Dumped chunk 1/1 for August nurilab DONE
Clean Succeed, Check your Gsheet
Cleaned September Nurilab DONE
Dumping succeed, Check your Gsheet
Dumped chunk 1/1 for September nurilab DONE
CSV: 9.733834505081177
ALL LOOPING DONE

# Check Completness Data
(Help PIC untuk check data per bulan nya Completed atau On Progress)

In [ ]:
# Check Completed Status

for month in months_list:
    df = redash_245[redash_245['month'] == month].copy()
    print(f'For {month} \n',df['granular_status'].value_counts(),'\n')

For July
 granular_status
Completed             6474
Cancelled               29
Returned to Sender      26
Name: count, dtype: int64

For August
 granular_status
Completed                  797
Arrived at Sorting Hub       4
Cancelled                    4
Returned to Sender           3
On Hold                      3
En-route to Sorting Hub      2
On Vehicle for Delivery      1
Name: count, dtype: int64

For September
 granular_status
Completed                  176
Arrived at Sorting Hub      78
Pending Pickup               8
On Vehicle for Delivery      6
On Hold                      1
Name: count, dtype: int64

# Send E-mail

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ## Email November

# print('>> Sending email....')

# from email.mime.text import MIMEText
# from email.mime.application import MIMEApplication
# from email.mime.multipart import MIMEMultipart
# from smtplib import SMTP
# import ssl
# import smtplib
# from pretty_html_table import build_table

# # Original email's message ID

# msg = MIMEMultipart()
# msg['Subject'] = 'Daily Parcel Report with POD Shipper PT Flexo Solusi indonesia (B2BR) - '+today_format
# msg['From'] = 'Ika Susanti'
# # msg['To'] = 'Kharisma Nuraisyah <kharisma.nuraisyah@ninjavan.co>'
# # msg['Cc'] = 'Sheilta Alphenia <sheilta.alphenia@ninjavan.co>'
# msg['To'] = 'Muhammad Hosim <muhammad.hosim@ninjavan.co>, Arfian Surya Wibawa <arfian.surya@ninjavan.co>, Herdiana Nurocta S <herdiana.nurocta@ninjavan.co>, Muhammad Alfi Maulana Azzarahwaan <alfi.azzarahwaan@ninjavan.co>'
# msg['Cc'] = 'Business Intelligence (ID) <ID-BI@ninjavan.co>, Kania Krisnanto <kania.krisnanto@ninjavan.co>, ID BI - Reporting <id-bi-reporting@ninjavan.co>'
# # msg['Bcc'] =# msg['Cc'] = '"Ops - Fleet Support (ID)" <id-ops-station-fleetsupport@ninjavan.co>, Kania Krisnanto <kania.krisnanto@ninjavan.co>'
# # msg['Bcc'] =

# #filename = 'test.xlsx'
# #fp = open(filename,'rb')
# #attachment = MIMEApplication(fp.read(),_subtype="xlsx")
# #fp.close()
# #attachment.add_header('Content-Disposition', 'attachment', filename=filename)
# #msg.attach(attachment)


# html = """\
# <html>
#   <body>
#     <p>Dear Team Corporate Sales,</p>

# <p>Berikut kami lampirkan Daily PT Flexo Solusi Indonesia Report with POD Periode {0}</p>
# <p><a href="{1}"> PT Flexo Solusi indonesia - Regular (B2BR) April 2025 (On Process)</a></p>
# <p><a href="{2}"> PT Flexo Solusi indonesia - NURILAB April 2025 (On Process)</a></p>
# <p>Data yang terlampir pada file tersebut merupakan data yang statusnya completed dan yang masih dalam proses pengiriman.</p>
# <p>Mohon untuk dapat dicek secara berkala setiap harinya.</p>

# <p><b> Regards,

# <br>Ika Susanti </b></p>

#   </body>
# </html>
# """.format((
#     month_format),url_month_1,url_month_1_nurilab)
# # ,url_month_2,url_month_2_nurilab)
# # ,url_month_3,url_month_3_nurilab)

# part1 = MIMEText(html, 'html')
# msg.attach(part1)
# to = 'muhammad.hosim@ninjavan.co', 'ID-BI@ninjavan.co', 'kania.krisnanto@ninjavan.co', 'arfian.surya@ninjavan.co', 'herdiana.nurocta@ninjavan.co', 'alfi.azzarahwaan@ninjavan.co', 'nindi.dwiprahasti@ninjavan.co','id-bi-reporting@ninjavan.co'
# # to = 'kharisma.nuraisyah@ninjavan.co'

# context = ssl.create_default_context()

# with smtplib.SMTP('smtp.gmail.com', 587) as server:
#     server.ehlo()
#     server.starttls(context=context)
#     server.ehlo()
#     server.login('ika.susanti@ninjavan.co', 'pyhzjmudrdsyazjk')
#     server.sendmail('ika.susanti@ninjavan.co',to, msg.as_string())

# print('>> Email SENT')

In [ ]:
print('>> Sending email....')

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import ssl
import smtplib
import time
from datetime import datetime

# Date Format
today_format2 = datetime.now().strftime('%d %b %Y')
# month_format = datetime.now().strftime('%B %Y')

# Recipients Information (loop per orang)
recipients = [
{'name': 'Muhammad Hosim', 'email': 'muhammad.hosim@ninjavan.co'},
{'name': 'Arfian Surya Wibawa', 'email': 'arfian.surya@ninjavan.co'},
{'name': 'Herdiana Nurocta S', 'email': 'herdiana.nurocta@ninjavan.co'},
{'name': 'Muhammad Alfi Maulana Azzarahwaan', 'email': 'alfi.azzarahwaan@ninjavan.co'},
{'name': 'Business Intelligence (ID)', 'email': 'ID-BI@ninjavan.co'},
{'name': 'Kania Krisnanto', 'email': 'kania.krisnanto@ninjavan.co'},
{'name': 'ID BI - Reporting', 'email': 'id-bi-reporting@ninjavan.co'},
              #  {'name': 'Griya Lalita Firdausy', 'email': 'griya.lalita@ninjavan.co'},
               {'name': 'As syifah Nurlaeli', 'email': 'assyifah.nurlaeli@ninjavan.co'}

]


# Sender Information
sender_email = "assyifah.nurlaeli@ninjavan.co"
sender_name = "As Syifah Nurlaeli"
password = "ysrbmxoihmbrpvli"

report_id = f"Flexo_Solution_Report {today_format2} "  # Ganti Nama Report

context = ssl.create_default_context()

for recipient in recipients:
    # print(f">> Start Sending Email...")

    msg = MIMEMultipart()
    msg['Subject'] = 'Daily Parcel Report with POD Shipper PT Flexo Solusi indonesia (B2BR) - '+today_format
    msg['From'] = f"{sender_name} <{sender_email}>"
    msg['To'] = 'Muhammad Hosim <muhammad.hosim@ninjavan.co>, Arfian Surya Wibawa <arfian.surya@ninjavan.co>, Herdiana Nurocta S <herdiana.nurocta@ninjavan.co>, Muhammad Alfi Maulana Azzarahwaan <alfi.azzarahwaan@ninjavan.co>'
    msg['Cc'] = 'Business Intelligence (ID) <ID-BI@ninjavan.co>, Kania Krisnanto <kania.krisnanto@ninjavan.co>, ID BI - Reporting <id-bi-reporting@ninjavan.co>'

    # Email tracking ID
    email_id = recipient['email']
    timestamp = int(time.time())

    tracking_url = (
        "https://script.google.com/macros/s/AKfycbwml48iKS5YqpULiY9mjDqKeUA4YBEaII80o0j65oX37gWdz18qR7qE6QvXlMZ0xKp8/exec"
        f"?user={report_id}&email={email_id}&ts={timestamp}"
    )

    tracking_pixel = f'<img src="{tracking_url}" width="1" height="1" style="display:block;" alt="." />'

    html = f"""
    <html>
  <body>
    <p>Dear Team Corporate Sales,</p>

<p>Berikut kami lampirkan Daily PT Flexo Solusi Indonesia Report with POD Periode {month_format}</p>
<p><a href="{url_month_1}"> PT Flexo Solusi indonesia - Regular (B2BR) Juli 2025 (On Process)</a></p>
<p><a href="{url_month_1_nurilab}"> PT Flexo Solusi indonesia - NURILAB Juli 2025 (On Process)</a></p>
<p><a href="{url_month_2}"> PT Flexo Solusi indonesia - Regular (B2BR) Agustus 2025 (On Process)</a></p>
<p><a href="{url_month_2_nurilab}"> PT Flexo Solusi indonesia - NURILAB Agustus 2025 (On Process)</a></p>
<p><a href="{url_month_3}"> PT Flexo Solusi indonesia - Regular (B2BR) September 2025 (On Process)</a></p>
<p><a href="{url_month_3_nurilab}"> PT Flexo Solusi indonesia - NURILAB September 2025 (On Process)</a></p>
<p>Data yang terlampir pada file tersebut merupakan data yang statusnya completed dan yang masih dalam proses pengiriman.</p>
<p>Mohon untuk dapat dicek secara berkala setiap harinya.</p>
    {tracking_pixel}

    <p><b> Regards,

    <br>As Syifah Nurlaeli </b></p>

  </body>
</html>
    """

    part1 = MIMEText(html, 'html')
    msg.attach(part1)

    with smtplib.SMTP('smtp.gmail.com', 587) as server:
        server.ehlo()
        server.starttls(context=context)
        server.ehlo()
        server.login(sender_email, password)
        server.sendmail(sender_email, recipient['email'], msg.as_string())

print('>> All emails sent!')

>> Sending email....
>> All emails sent!